# Week 03 Notes

## Review Arrays and Lists

### Review of Creating Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.arange(0,11,1)   # start, stop(not inclusing), step
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
c = np.arange(11)       # default start, stop=11, default step
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
d = np.linspace(0,360,9) # start, stop, number of elements
print(d)

[  0.  45.  90. 135. 180. 225. 270. 315. 360.]


### Review Indexing Arrays

In [6]:
d = np.linspace(0,360,9) # start, stop, number of elements
print(d)

[  0.  45.  90. 135. 180. 225. 270. 315. 360.]


In [7]:
# pull out the 3rd angle (angle at index=2)
d[2]

90.0

In [8]:
# pull out 315
print(d[7])
print(d[-2])   #2nd to last value

315.0
315.0


In [9]:
# pull out the last element, 360
d[-1]

360.0

### Indexing 2D arrays

In [10]:
f = np.array([[3,4,5],[8,9,10]])  #
print(f)

[[ 3  4  5]
 [ 8  9 10]]


In [11]:
f = np.array([3,4,5,8,9,10])
print(f)
f.shape=(2,3)
print(f)

[ 3  4  5  8  9 10]
[[ 3  4  5]
 [ 8  9 10]]


In [12]:
# pull the 4 out
f[0,1]  #row,col

4

In [13]:
# pull out the 10
f[1,2]

10

In [14]:
# pull out the 5
f[0,-1]  #row 0, last column (col=-1)

5

In [15]:
g = np.array([1,2,3,4,5]) # if array has prime number of elememts, it can't be reshaped into a 2D array, just into a column (instead of a row)
g.shape=(5,1)

In [16]:
# Would this be the same? Create a 2D array? ([3,4,5]+[8,9,10]) , No.
print([3,4,5]+[8,9,10])

[3, 4, 5, 8, 9, 10]


In [17]:
h = np.arange(27)
print(h)
h.shape=(3,3,3)
print(h)
# pull out 25 [sheet,row,col]
h[2,2,1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


25

### Review of array slicing

In [18]:
f = np.array([3,4,5,8,9,10])
print(f)
f.shape=(2,3)
print(f)

[ 3  4  5  8  9 10]
[[ 3  4  5]
 [ 8  9 10]]


In [19]:
# entire first row
f[0,0:3:1]   #start:stop:step

array([3, 4, 5])

In [20]:
f[0,:3:1]

array([3, 4, 5])

In [21]:
f[0,0:3]

array([3, 4, 5])

In [22]:
f[0,:]

array([3, 4, 5])

In [23]:

f = np.array([3,4,5,8,9,10])
f.shape=(2,3)
print(f)

[[ 3  4  5]
 [ 8  9 10]]


In [24]:
# pull out the last column
f[0:2:1,2]   # row start=0, stop=2, count by = 2.  , col = 2

array([ 5, 10])

In [25]:
f[0:2:1,-1] # last col

array([ 5, 10])

In [26]:
f[:,2]    # all rows, index=2 column

array([ 5, 10])

### Masking, Broadcasting

In [27]:
f = np.array([3,4,5,8,9,10])
f.shape=(2,3)
print(f)

[[ 3  4  5]
 [ 8  9 10]]


In [28]:
# I know there is a 5 in the array, where is it
loc = np.where(f==5)
print(loc)  # the number 5 is at row=0, col=2

(array([0]), array([2]))


In [29]:
f[loc]  # return the value at the location found

array([5])

In [30]:
# use a boolean mask to find the 5


In [31]:
# I know there is a 5 in the array, where is it
loc = np.where(f==5)
print(loc)  # the number 5 is at row=0, col=2
print(type(loc))  # the output of np.where is a tuple with one element

(array([0]), array([2]))
<class 'tuple'>


In [32]:
loc[0]

array([0])

In [33]:
loc[1]

array([2])

In [34]:
loc[0][0]

0

In [35]:
loc[1][0]

2

In [36]:
loc

(array([0]), array([2]))

In [37]:
n = np.array([5.])
print(n)

[5.]


In [38]:
np.__version__

'1.21.2'

In [39]:
import sys
sys.version

'3.9.7 (default, Sep 16 2021, 08:50:36) \n[Clang 10.0.0 ]'

### Boolean Mask

In [40]:
f = np.array([3,4,5,8,9,10])
f.shape=(2,3)
print(f)

[[ 3  4  5]
 [ 8  9 10]]


In [41]:
# pull out all the numbers greater than 6
mask = f>6
print(mask)

[[False False False]
 [ True  True  True]]


In [42]:
f[mask]

array([ 8,  9, 10])

In [47]:
a = np.array([0,1,2,3,-999999999])
# only pull out the "resonable numbers" if reasonable is amount of rainfall
mask2 = a>=0
a[mask2]

array([0, 1, 2, 3])

### Getting Help in Jupyter notebook

Help on official Jupyter documentation

http://jupyter.readthedocs.io/en/latest/

Get help using dir in Jupyter on functions, methods,variables or objects

In [48]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [49]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


Get help using tab key after objectname.[tab] in Jupter cell

In [51]:
import sys
sys.version

'3.9.7 (default, Sep 16 2021, 08:50:36) \n[Clang 10.0.0 ]'

In [52]:
import numpy as np
np.where()

TypeError: where() missing 1 required positional argument: 'condition'

In [53]:
import math
help(math.tan)

Help on built-in function tan in module math:

tan(x, /)
    Return the tangent of x (measured in radians).



In [54]:
import numpy as np
help(np.tan)

Help on ufunc:

tan = <ufunc 'tan'>
    tan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Compute tangent element-wise.
    
    Equivalent to ``np.sin(x)/np.cos(x)`` element-wise.
    
    Parameters
    ----------
    x : array_like
        Input array.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is create

In [55]:
# make sure the cat_in_hat_words.txt is in the same directory as this running jupyter notebiook

In [56]:
%ls

cat_in_hat_words.txt
lab_03_notes.ipynb
week_03_notes.ipynb
week_03_notes_outline.ipynb
week_03_notes_review_arrays_and_lists.ipynb


In [57]:
with open('cat_in_hat_words.txt', 'r') as f:
    words = [line.strip() for line in f.readlines()]
print(words)

['a', 'about', 'after', 'all', 'always', 'and', 'another', 'any', 'are', 'as', 'asked', 'at', 'away', 'back', 'bad', 'ball', 'be', 'bed', 'bent', 'bet', 'big', 'bit', 'bite', 'book', 'books', 'bow', 'box', 'bump', 'bumps', 'but', 'by', 'ca', 'cake', 'call', 'came', 'can', 'cat', 'cold', 'come', 'could', 'cup', 'day', 'dear', 'deep', 'did', 'dish', 'do', 'dots', 'down', 'fall', 'fan', 'fast', 'fear', 'fell', 'find', 'fish', 'fly', 'for', 'fox', 'from', 'fun', 'funny', 'game', 'games', 'gave', 'get', 'give', 'go', 'gone', 'good', 'got', 'gown', 'had', 'hall', 'hand', 'hands', 'has', 'hat', 'have', 'he', 'head', 'hear', 'her', 'here', 'high', 'him', 'his', 'hit', 'hold', 'home', 'hook', 'hop', 'hops', 'house', 'how', 'i', 'if', 'in', 'into', 'is', 'it', 'jump', 'jumps', 'kicks', 'kind', 'kinds', 'kite', 'kites', 'know', 'last', 'let', 'like', 'lit', 'litte', 'little', 'look', 'looked', 'lot', 'lots', 'made', 'make', 'man', 'mat', 'me', 'mess', 'milk', 'mind', 'mother', 'my', 'near', 'net'

In [60]:
# print "a" "ball"
words[0] + words[15]

'aball'

In [ ]:
words.